### ISSUE TITLE
Submit to Komodo Resources

### ISSUE THREAD

**Issue by Naatan** [ivoryworks/komodo-markdown-aid#1]
Hi there, awesome macro! I had been thinking of creating one just like it, glad I don't have to :) I look forward to using yours.

I think many users will appreciate your work on this, so why not submit it to the Komodo Resources section? :) https://github.com/Komodo/Komodo-Resources

**Comment by ivoryworks** [comment]
Hi there Thank you for finding my macros. 

By all means, I want to add to the  Komodo Resources section this macro.

**Comment by Naatan** [comment]
I've added your macro here: https://github.com/Komodo/Komodo-Resources/commit/739148909e2a86a5b3722833b232ace660ea44c3

Please feel free to fork the Komodo-Resources repo and submit pull requests for any other resources you might want to add in the future.

Your macro will be available on the Resources section in the next hour or so, note that for it to show download counts and an easy download button you should add a Release to your repo at this page: https://github.com/ivoryworks/komodo-markdown-aid/releases

Thanks for the great macro! :)
